### ISSUE TITLE
receive fn not 1.3 compatible

### ISSUE THREAD

**Issue by postspectacular** [cemerick/bandalore#1]
Hi Chas, firstly thanks for the super nice wrapper! Here's a little bug fix for the `(receive)` function in order to address the ClassCastException under Clojure 1.3: java.lang.Long cannot be cast to java.lang.Integer...

``` clojure
; line 116
(.withMaxNumberOfMessages (-> limit (min 10) (max 1)))
```

Should be using a cast to an int (or rather boxed Integer -> http://dev.clojure.org/jira/browse/CLJ-820)...

``` clojure
(.withMaxNumberOfMessages (-> limit (min 10) (max 1) Integer.))
```

Thanks!

**Comment by cemerick** [comment]
Sorry for the delay in resolving this; I've not been using SQS lately.

The release containing this fix (`[com.cemerick/bandalore "0.0.2"]`) should show up in maven central sometime today.
