### ISSUE TITLE
Add ability to change AWS region for bandalore

### ISSUE THREAD

**Issue by dakrone** [cemerick/bandalore#10]
Bandalore seems to use `us-east-1` by default, and I haven't discovered a way to change it. It'd be nice to be able to configure it for other regions such as `eu-west-1` and so on.

**Comment by cemerick** [comment]
No special support from bandalore is required. See https://github.com/cemerick/bandalore/issues/8#issuecomment-42412875

**Comment by dakrone** [comment]
Whoops, meant to post the comment I put on #8 here (about adding a comment to this effect in the readme).
