### ISSUE TITLE
Using a very old version of Amazon's API

### ISSUE THREAD

**Issue by nanafwu** [cemerick/bandalore#2]
Any chance you could update the version of Amazon's SDK you are using? I'm getting conflicts with the 1.3.9 version that I am using regarding the constructors for CreateQueueRequest. It seems that they have updated it since 1.1.5.

**Comment by gzeureka** [comment]
Yes, seems the aws api has been changed and I got this:

CompilerException java.lang.IllegalArgumentException: No matching ctor found for class com.amazonaws.services.sqs.model.CreateQueueRequest, compiling:(cemerick/bandalore.clj:36)

**Comment by joaosal** [comment]
Any ideas for this I am having the same error?

**Comment by cemerick** [comment]
This is fixed on master now, and a new release is working its way through maven central: `[com.cemerick/bandalore "0.0.3"]`.

There are a number of features in the newer AWS APIs for SQS that Bandalore does not yet support.  [Please help if you can.](3)
