### ISSUE TITLE
is there a region support?

### ISSUE THREAD

**Issue by Jae** [cemerick/bandalore#8]
I've just had a quick glance of the source code of create-client. Is there a region support without having to set a region on AmazonSQSClient create-client returns?

**Comment by Jae** [comment]
ah don't worry, it looks like it's happy to receive message from any region by queue url anyway.

**Comment by campeterson** [comment]
I'd love to see some sample code on how this is done.

**Comment by cemerick** [comment]
Region can be controlled via the client returned by `create-client`: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AmazonWebServiceClient.html#setRegion%28com.amazonaws.regions.Region%29

**Comment by dakrone** [comment]
@cemerick great thanks, can you add a blurb in the readme about this for future users?
